name: iOS Build

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Build target'
        required: true
        default: 'arm64-apple-ios'
        type: choice
        options:
          - arm64-apple-ios
          - arm64-apple-ios-macabi
          - arm64-apple-xros
          - arm64-apple-tvos

jobs:
  build:
    name: Build LuckySpeeder
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          chmod +x build.sh
          bash build.sh ${{ github.event.inputs.target }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LuckySpeeder-${{ github.event.inputs.target }}
          path: out/*/LuckySpeeder.dylib
          retention-days: 7
